name: Test2

on:
    pull_request:
        branches:
            - staging
        types:
            - opened
            - synchronize

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Set empty string
              id: set
              run: |
                echo "##[set-output name=targets;]$(echo '')"

            - name: debug
              run: |
                echo ${{ steps.set.outputs.targets }}

            - name: debug 2
              if: ${{ steps.set.outputs.targets == '' }}
              run: exit 1
                

            - name: debug 3
              if: ${{ steps.set.outputs.targets == '0' }}
              run: |
                echo "empty string with 0 string"

            - name: final
              run: |
                echo "final step"