name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
    clear-deploy-file:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                ref: "staging"

            - name: Clear deploy file
              run: echo -n "" > deploy.txt
              
            - uses: EndBug/add-and-commit@v9
              with:
                add: "."
                message: 'Deployed Production'
                default_author: github_actions
