name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
    clear-deploy-file:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                ref: "staging"

            - name: Clear deploy file
              run: echo -n "" > deploy.txt

            - name: Create Pull Request
              id: cpr
              uses: peter-evans/create-pull-request@v5
              with:
                commit-message: |
                  Deployed Production


                  skip-checks: true
                branch: clear-deploy-file
                title: 'Clear deploy.txt'
                body: |
                  Deployed Production
                base: staging

            - name: Disable PR review
              run: |
                curl -L \
                -X PATCH \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}"\
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/qashier-ray-foo/test-github-action-update-file/branches/staging/protection/required_pull_request_reviews \
                -d '{"require_code_owner_reviews": false, "required_approving_review_count": 0}'

            - name: Merge PR
              run: |
                curl -L \
                -X PUT \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}"\
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/qashier-ray-foo/test-github-action-update-file/pulls/${{steps.cpr.outputs.pull-request-number}}/merge

            - name: Re-enable PR review
              run: |
                curl -L \
                -X PATCH \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}"\
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/qashier-ray-foo/test-github-action-update-file/branches/staging/protection/required_pull_request_reviews \
                -d '{"require_code_owner_reviews": true, "required_approving_review_count": 2}'