name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
    clear-deploy-file:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                ref: "staging"

            - name: Clear deploy file
              run: echo -n "" > deploy.txt

            - name: Create Pull Request
              id: cpr
              uses: peter-evans/create-pull-request@v5
              with:
                commit-message: |
                  Deployed Production


                  skip-checks: true
                branch: clear-deploy-file
                title: 'Clear deploy.txt'
                body: |
                  Deployed Production
                base: staging

            - name: Merge PR
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: gh pr merge ${{steps.cpr.outputs.pull-request-number}} --admin